const countries = [
    { n: "Afghanistan", s: "افغانستان", c: "ps", f: "🇦🇫" }, 
    { n: "Albania", s: "Shqipëria", c: "sq", f: "🇦🇱" },
    { n: "Algeria", s: "الجزائر", c: "ar", f: "🇩🇿" }, 
    { n: "Andorra", s: "Andorra", c: "ca", f: "🇦🇩" },
    { n: "Angola", s: "Angola", c: "pt", f: "🇦🇴" }, 
    { n: "Antigua and Barbuda", s: "Antigua", c: "en", f: "🇦🇬" },
    { n: "Argentina", s: "Argentina", c: "es", f: "🇦🇷" }, 
    { n: "Armenia", s: "Հայաստան", c: "hy", f: "🇦🇲" },
    { n: "Australia", s: "Australia", c: "en", f: "🇦🇺" }, 
    { n: "Austria", s: "Österreich", c: "de", f: "🇦🇹" },
    { n: "Azerbaijan", s: "Azərbaycan", c: "az", f: "🇦🇿" }, 
    { n: "Bahamas", s: "Bahamas", c: "en", f: "🇧🇸" },
    { n: "Bahrain", s: "البحرين", c: "ar", f: "🇧🇭" }, 
    { n: "Bangladesh", s: "বাংলাদেশ", c: "bn", f: "🇧🇩" },
    { n: "Barbados", s: "Barbados", c: "en", f: "🇧🇧" }, 
    { n: "Belarus", s: "Беларусь", c: "be", f: "🇧🇾" },
    { n: "Belgium", s: "België", c: "nl", f: "🇧🇪" }, 
    { n: "Belize", s: "Belize", c: "en", f: "🇧🇿" },
    { n: "Benin", s: "Bénin", c: "fr", f: "🇧🇯" }, 
    { n: "Bhutan", s: "འབྲུག་ཡུལ་", c: "dz", f: "🇧🇹" },
    { n: "Bolivia", s: "Bolivia", c: "es", f: "🇧🇴" }, 
    { n: "Bosnia and Herzegovina", s: "Bosna", c: "bs", f: "🇧🇦" },
    { n: "Botswana", s: "Botswana", c: "en", f: "🇧🇼" }, 
    { n: "Brazil", s: "Brasil", c: "pt", f: "🇧🇷" },
    { n: "Brunei", s: "Brunei", c: "ms", f: "🇧🇳" }, 
    { n: "Bulgaria", s: "България", c: "bg", f: "🇧🇬" },
    { n: "Burkina Faso", s: "Burkina Faso", c: "fr", f: "🇧🇫" }, 
    { n: "Burundi", s: "Burundi", c: "fr", f: "🇧🇮" },
    { n: "Cambodia", s: "កម្ពុជា", c: "km", f: "🇰🇭" }, 
    { n: "Cameroon", s: "Cameroun", c: "fr", f: "🇨🇲" },
    { n: "Canada", s: "Canada", c: "en", f: "🇨🇦" }, 
    { n: "Cape Verde", s: "Cabo Verde", c: "pt", f: "🇨🇻" },
    { n: "Central African Republic", s: "République centrafricaine", c: "fr", f: "🇨🇫" }, 
    { n: "Chad", s: "Tchad", c: "fr", f: "🇹🇩" },
    { n: "Chile", s: "Chile", c: "es", f: "🇨🇱" }, 
    { n: "China", s: "中国", c: "zh-CN", f: "🇨🇳" },
    { n: "Colombia", s: "Colombia", c: "es", f: "🇨🇴" }, 
    { n: "Comoros", s: "القمر", c: "ar", f: "🇰🇲" },
    { n: "Congo (Brazzaville)", s: "Congo", c: "fr", f: "🇨🇬" }, 
    { n: "Congo (Kinshasa)", s: "Congo", c: "sw", f: "🇨🇩" },
    { n: "Costa Rica", s: "Costa Rica", c: "es", f: "🇨🇷" }, 
    { n: "Croatia", s: "Hrvatska", c: "hr", f: "🇭🇷" },
    { n: "Cuba", s: "Cuba", c: "es", f: "🇨🇺" }, 
    { n: "Cyprus", s: "Κύπρος", c: "el", f: "🇨🇾" },
    { n: "Czech Republic", s: "Česko", c: "cs", f: "🇨🇿" }, 
    { n: "Denmark", s: "Danmark", c: "da", f: "🇩🇰" },
    { n: "Djibouti", s: "Djibouti", c: "fr", f: "🇩🇯" }, 
    { n: "Dominica", s: "Dominica", c: "en", f: "🇩🇲" },
    { n: "Dominican Republic", s: "República Dominicana", c: "es", f: "🇩🇴" }, 
    { n: "Ecuador", s: "Ecuador", c: "es", f: "🇪🇨" },
    { n: "Egypt", s: "مصر", c: "ar", f: "🇪🇬" }, 
    { n: "El Salvador", s: "El Salvador", c: "es", f: "🇸🇻" },
    { n: "Equatorial Guinea", s: "Guinea Ecuatorial", c: "es", f: "🇬🇶" }, 
    { n: "Eritrea", s: "Eritrea", c: "ti", f: "🇪🇷" },
    { n: "Estonia", s: "Eesti", c: "et", f: "🇪🇪" }, 
    { n: "Eswatini", s: "Eswatini", c: "en", f: "🇸🇿" },
    { n: "Ethiopia", s: "ኢትዮጵያ", c: "am", f: "🇪🇹" }, 
    { n: "Fiji", s: "Fiji", c: "en", f: "🇫🇯" },
    { n: "Finland", s: "Suomi", c: "fi", f: "🇫🇮" }, 
    { n: "France", s: "France", c: "fr", f: "🇫🇷" },
    { n: "Gabon", s: "Gabon", c: "fr", f: "🇬🇦" }, 
    { n: "Gambia", s: "Gambia", c: "en", f: "🇬🇲" },
    { n: "Georgia", s: "საქართველო", c: "ka", f: "🇬🇪" }, 
    { n: "Germany", s: "Deutschland", c: "de", f: "🇩🇪" },
    { n: "Ghana", s: "Ghana", c: "en", f: "🇬🇭" }, 
    { n: "Greece", s: "Ελλάδα", c: "el", f: "🇬🇷" },
    { n: "Grenada", s: "Grenada", c: "en", f: "🇬🇩" }, 
    { n: "Guatemala", s: "Guatemala", c: "es", f: "🇬🇹" },
    { n: "Guinea", s: "Guinée", c: "fr", f: "🇬🇳" }, 
    { n: "Guinea-Bissau", s: "Guiné-Bissau", c: "pt", f: "🇬🇼" },
    { n: "Guyana", s: "Guyana", c: "en", f: "🇬🇾" }, 
    { n: "Haiti", s: "Haïti", c: "fr", f: "🇭🇹" },
    { n: "Honduras", s: "Honduras", c: "es", f: "🇭🇳" }, 
    { n: "Hungary", s: "Magyarország", c: "hu", f: "🇭🇺" },
    { n: "Iceland", s: "Ísland", c: "is", f: "🇮🇸" }, 
    { n: "India", s: "भारत (India)", c: "hi", f: "🇮🇳" },
    { n: "Indonesia", s: "Indonesia", c: "id", f: "🇮🇩" }, 
    { n: "Iran", s: "ایران", c: "fa", f: "🇮🇷" },
    { n: "Iraq", s: "العراق", c: "ar", f: "🇮🇶" }, 
    { n: "Ireland", s: "Ireland", c: "en", f: "🇮🇪" },
    { n: "Israel", s: "יִשְׂרָאֵל", c: "he", f: "🇮🇱" }, 
    { n: "Italy", s: "Italia", c: "it", f: "🇮🇹" },
    { n: "Jamaica", s: "Jamaica", c: "en", f: "🇯🇲" }, 
    { n: "Japan", s: "日本", c: "ja", f: "🇯🇵" },
    { n: "Jordan", s: "الأردن", c: "ar", f: "🇯🇴" }, 
    { n: "Kazakhstan", s: "Қазақстан", c: "kk", f: "🇰🇿" },
    { n: "Kenya", s: "Kenya", c: "sw", f: "🇰🇪" }, 
    { n: "Kiribati", s: "Kiribati", c: "en", f: "🇰🇮" },
    { n: "Korea, North", s: "조선", c: "ko", f: "🇰🇵" }, 
    { n: "Korea, South", s: "한국", c: "ko", f: "🇰🇷" },
    { n: "Kuwait", s: "الكويت", c: "ar", f: "🇰🇼" }, 
    { n: "Kyrgyzstan", s: "Кыргызстан", c: "ky", f: "🇰🇬" },
    { n: "Laos", s: "ລາວ", c: "lo", f: "🇱🇦" }, 
    { n: "Latvia", s: "Latvija", c: "lv", f: "🇱🇻" },
    { n: "Lebanon", s: "لبنان", c: "ar", f: "🇱🇧" }, 
    { n: "Lesotho", s: "Lesotho", c: "en", f: "🇱🇸" },
    { n: "Liberia", s: "Liberia", c: "en", f: "🇱🇷" }, 
    { n: "Libya", s: "ليبيا", c: "ar", f: "🇱🇾" },
    { n: "Liechtenstein", s: "Liechtenstein", c: "de", f: "🇱🇮" }, 
    { n: "Lithuania", s: "Lietuva", c: "lt", f: "🇱🇹" },
    { n: "Luxembourg", s: "Luxembourg", c: "lb", f: "🇱🇺" }, 
    { n: "Madagascar", s: "Madagasikara", c: "mg", f: "🇲🇬" },
    { n: "Malawi", s: "Malawi", c: "en", f: "🇲🇼" }, 
    { n: "Malaysia", s: "Malaysia", c: "ms", f: "🇲🇾" },
    { n: "Maldives", s: "ދިވެހިރާއްޖެ", c: "dv", f: "🇲🇻" }, 
    { n: "Mali", s: "Mali", c: "fr", f: "🇲🇱" },
    { n: "Malta", s: "Malta", c: "mt", f: "🇲🇹" }, 
    { n: "Marshall Islands", s: "Marshall Islands", c: "en", f: "🇲🇭" },
    { n: "Mauritania", s: "موريتانيا", c: "ar", f: "🇲🇷" }, 
    { n: "Mauritius", s: "Maurice", c: "fr", f: "🇲🇺" },
    { n: "Mexico", s: "México", c: "es", f: "🇲🇽" }, 
    { n: "Micronesia", s: "Micronesia", c: "en", f: "🇫🇲" },
    { n: "Moldova", s: "Moldova", c: "ro", f: "🇲🇩" }, 
    { n: "Monaco", s: "Monaco", c: "fr", f: "🇲🇨" },
    { n: "Mongolia", s: "Монгол", c: "mn", f: "🇲🇳" }, 
    { n: "Montenegro", s: "Crna Gora", c: "cnr", f: "🇲🇪" },
    { n: "Morocco", s: "المغرب", c: "ar", f: "🇲🇦" }, 
    { n: "Mozambique", s: "Moçambique", c: "pt", f: "🇲🇿" },
    { n: "Myanmar", s: "မြန်မာ", c: "my", f: "🇲🇲" }, 
    { n: "Namibia", s: "Namibia", c: "en", f: "🇳🇦" },
    { n: "Nauru", s: "Naoero", c: "na", f: "🇳🇷" }, 
    { n: "Nepal", s: "नेपाल", c: "ne", f: "🇳🇵" },
    { n: "Netherlands", s: "Nederland", c: "nl", f: "🇳🇱" }, 
    { n: "New Zealand", s: "New Zealand", c: "en", f: "🇳🇿" },
    { n: "Nicaragua", s: "Nicaragua", c: "es", f: "🇳🇮" }, 
    { n: "Niger", s: "Niger", c: "fr", f: "🇳🇪" },
    { n: "Nigeria", s: "Nigeria", c: "en", f: "🇳🇬" }, 
    { n: "North Macedonia", s: "Северна Македонија", c: "mk", f: "🇲🇰" },
    { n: "Norway", s: "Norge", c: "no", f: "🇳🇴" }, 
    { n: "Oman", s: "عمان", c: "ar", f: "🇴🇲" },
    { n: "Pakistan", s: "پاکستان", c: "ur", f: "🇵🇰" }, 
    { n: "Palau", s: "Palau", c: "en", f: "🇵🇼" },
    { n: "Panama", s: "Panamá", c: "es", f: "🇵🇦" }, 
    { n: "Papua New Guinea", s: "Papua New Guinea", c: "en", f: "🇵🇬" },
    { n: "Paraguay", s: "Paraguay", c: "es", f: "🇵🇾" }, 
    { n: "Peru", s: "Perú", c: "es", f: "🇵🇪" },
    { n: "Philippines", s: "Pilipinas", c: "tl", f: "🇵🇭" }, 
    { n: "Poland", s: "Polska", c: "pl", f: "🇵🇱" },
    { n: "Portugal", s: "Portugal", c: "pt", f: "🇵🇹" }, 
    { n: "Qatar", s: "قطر", c: "ar", f: "🇶🇦" },
    { n: "Romania", s: "România", c: "ro", f: "🇷🇴" }, 
    { n: "Russia", s: "Россия", c: "ru", f: "🇷🇺" },
    { n: "Rwanda", s: "Rwanda", c: "rw", f: "🇷🇼" }, 
    { n: "Saint Kitts and Nevis", s: "Saint Kitts", c: "en", f: "🇰🇳" },
    { n: "Saint Lucia", s: "Saint Lucia", c: "en", f: "🇱🇨" }, 
    { n: "Saint Vincent", s: "Saint Vincent", c: "en", f: "🇻🇨" },
    { n: "Samoa", s: "Samoa", c: "sm", f: "🇼🇸" }, 
    { n: "San Marino", s: "San Marino", c: "it", f: "🇸🇲" },
    { n: "Sao Tome and Principe", s: "São Tomé", c: "pt", f: "🇸🇹" }, 
    { n: "Saudi Arabia", s: "السعودية", c: "ar", f: "🇸🇦" },
    { n: "Senegal", s: "Sénégal", c: "fr", f: "🇸🇳" }, 
    { n: "Serbia", s: "Србија", c: "sr", f: "🇷🇸" },
    { n: "Seychelles", s: "Seychelles", c: "fr", f: "🇸🇨" }, 
    { n: "Sierra Leone", s: "Sierra Leone", c: "en", f: "🇸🇱" },
    { n: "Singapore", s: "Singapore", c: "en", f: "🇸🇬" }, 
    { n: "Slovakia", s: "Slovensko", c: "sk", f: "🇸🇰" },
    { n: "Slovenia", s: "Slovenija", c: "sl", f: "🇸🇮" }, 
    { n: "Solomon Islands", s: "Solomon Islands", c: "en", f: "🇸🇧" },
    { n: "Somalia", s: "Soomaaliya", c: "so", f: "🇸🇴" }, 
    { n: "South Africa", s: "South Africa", c: "en", f: "🇿🇦" },
    { n: "South Sudan", s: "South Sudan", c: "en", f: "🇸🇸" }, 
    { n: "Spain", s: "España", c: "es", f: "🇪🇸" },
    { n: "Sri Lanka", s: "ශ්‍රී ලංකාව", c: "si", f: "🇱🇰" }, 
    { n: "Sudan", s: "السودان", c: "ar", f: "🇸🇩" },
    { n: "Suriname", s: "Suriname", c: "nl", f: "🇸🇷" }, 
    { n: "Sweden", s: "Sverige", c: "sv", f: "🇸🇪" },
    { n: "Switzerland", s: "Schweiz", c: "de", f: "🇨🇭" }, 
    { n: "Syria", s: "سوريا", c: "ar", f: "🇸🇾" },
    { n: "Taiwan", s: "台灣", c: "zh-TW", f: "🇹🇼" }, 
    { n: "Tajikistan", s: "Тоҷикистон", c: "tg", f: "🇹🇯" },
    { n: "Tanzania", s: "Tanzania", c: "sw", f: "🇹🇿" }, 
    { n: "Thailand", s: "ไทย", c: "th", f: "🇹🇭" },
    { n: "Timor-Leste", s: "Timor-Leste", c: "pt", f: "🇹🇱" }, 
    { n: "Togo", s: "Togo", c: "fr", f: "🇹🇬" },
    { n: "Tonga", s: "Tonga", c: "en", f: "🇹🇴" }, 
    { n: "Trinidad and Tobago", s: "Trinidad", c: "en", f: "🇹🇹" },
    { n: "Tunisia", s: "تونس", c: "ar", f: "🇹🇳" }, 
    { n: "Turkey", s: "Türkiye", c: "tr", f: "🇹🇷" },
    { n: "Turkmenistan", s: "Türkmenistan", c: "tk", f: "🇹🇲" }, 
    { n: "Tuvalu", s: "Tuvalu", c: "en", f: "🇹🇻" },
    { n: "Uganda", s: "Uganda", c: "sw", f: "🇺🇬" }, 
    { n: "Ukraine", s: "Україна", c: "uk", f: "🇺🇦" },
    { n: "UAE", s: "الإمارات", c: "ar", f: "🇦🇪" }, 
    { n: "UK", s: "United Kingdom", c: "en", f: "🇬🇧" },
    { n: "USA", s: "United States", c: "en", f: "🇺🇸" }, 
    { n: "Uruguay", s: "Uruguay", c: "es", f: "🇺🇾" },
    { n: "Uzbekistan", s: "Oʻzbekiston", c: "uz", f: "🇺🇿" }, 
    { n: "Vanuatu", s: "Vanuatu", c: "bi", f: "🇻🇺" },
    { n: "Vatican City", s: "Vaticano", c: "it", f: "🇻🇦" }, 
    { n: "Venezuela", s: "Venezuela", c: "es", f: "🇻🇪" },
    { n: "Vietnam", s: "Việt Nam", c: "vi", f: "🇻🇳" }, 
    { n: "Yemen", s: "اليمن", c: "ar", f: "🇾🇪" },
    { n: "Zambia", s: "Zambia", c: "en", f: "🇿🇲" }, 
    { n: "Zimbabwe", s: "Zimbabwe", c: "en", f: "🇿🇼" }
];
